---
deployment:
  tasks:
    - /bin/cp -R assets *.html *.css *.js *.pdf *.jpg /home/medicalc/public_html/
    - /bin/cp -R api package.json package-lock.json .env config.js /home/medicalc/app/
    - mkdir -p /home/medicalc/app/tmp
    - touch /home/medicalc/app/tmp/restart.txt
