// Use explicit path so dotenv always finds .env regardless of cwd
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const connectDB = require('./config/db');
const { errorHandler, notFound } = require('./middleware/errorMiddleware');

const healthRoutes = require('./routes/healthRoutes');
const studentRoutes = require('./routes/studentRoutes');
const staffRoutes = require('./routes/staffRoutes');
const adminRoutes = require('./routes/adminRoutes');
const contactRoutes = require('./routes/contactRoutes');
const newsRoutes = require('./routes/newsRoutes');
const eventRoutes = require('./routes/eventRoutes');

const app = express();

// Middleware
app.use(helmet({
    contentSecurityPolicy: false,
    crossOriginResourcePolicy: { policy: "cross-origin" }
}));
app.use(cors({
    origin: true,
    credentials: true
}));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));

// Serve uploaded public files securely, while blocking direct access to private student documents
app.use('/api/uploads', (req, res, next) => {
    // Student document filenames generated by Multer start with 'documents-'
    const filename = path.basename(req.path);
    if (!filename || /^documents-/i.test(filename) || filename.startsWith('.')) {
        return res.status(403).json({ success: false, message: 'Access denied. Student documents must be accessed via authorized portal routes.' });
    }
    next();
}, express.static(path.join(__dirname, 'uploads'), {
    dotfiles: 'deny',
    index: false
}));

// Mount API Routes
app.use('/api/health', healthRoutes);
app.use('/api/students', studentRoutes);
app.use('/api/staff', staffRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/contact', contactRoutes);
app.use('/api/news', newsRoutes);
app.use('/api/events', eventRoutes);

// Serve static frontend files (HTML, CSS, JS, images, uploads)
app.use(express.static(path.join(__dirname, '..')));

// Error Handling Middleware
app.use(notFound);
app.use(errorHandler);

const PORT = process.env.PORT || 5000;

// Start server, then connect to DB in background
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
    // Connect to DB after server is running
    connectDB().catch(err => console.error('DB connection failed:', err.message));
});

module.exports = app;
